module3-task1 23.12
htmlacademy-adaptive/1868525-pink-24 pull request #11
Opened 2021-12-23 11:02 UTC by tonkovidav

2021-12-25 18:21 UTC, ozil07 requested changes

2021-12-25 18:21 UTC, ozil07 commented on source/less/global/global.less
> +  font-family: "Open Sans", sans-serif;
Добавь доп шрифт из того семейства, желательно веб безопасный

2021-12-25 18:21 UTC, ozil07 commented on source/less/components/form/form-wrapper.less
> +  background-image: url("../../../img/mobile-back.png");
Исправь пути у фоновых изображений, относительно файла сборки

2021-12-28 10:30 UTC, tonkovidav commented on source/form.html
> +      <input class="main-form__data-text" type="text" id="name" placeholder="Введите ваше имя*">
Для чего нам name если есть id и for?

2021-12-28 10:34 UTC, tonkovidav commented on source/less/style.less
> +@import "./components/form/form-success.less";
Стили разбиты на блоки. Название страницы прикручено для удобства работы. Или удалить эти приставки и оставить просто блоки и не заморачиваться?

2021-12-28 21:50 UTC, ozil07 commented on source/form.html
> +      <input class="main-form__data-text" type="text" id="name" placeholder="Введите ваше имя*">
id и for связывает поле на странице, чтобы при клике по метке происходил фокус на поле которое указано в атрибуте for, а name используется для того, когда передаются данные на сервер, можно было получить их по названию заданному в атрибуте name

2021-12-28 22:14 UTC, ozil07 reviewed
Используй переменные в стилях, подключи шрифты одним из способов, используй переменные в less

2021-12-28 22:14 UTC, ozil07 commented on source/catalog.html
> +  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
Используй один способ подключения шрифтов

2021-12-28 22:14 UTC, ozil07 commented on source/less/global/global.less
> +}
Используй один из способов подключения шрифтов

2021-12-28 22:14 UTC, ozil07 commented on source/less/style.less
> +@import "./components/form/form-success.less";
Можно оставить, но лучше почитай про [бем](https://ru.bem.info/)

2021-12-28 22:14 UTC, ozil07 commented on source/less/components/form/form-checklist.less
> +  background-color: f2f2f2;
Забыл решетку в значении цвета

2021-12-29 12:28 UTC, tonkovidav commented on source/form.html
> +      <input class="main-form__data-text" type="text" id="name" placeholder="Введите ваше имя*">
понял теперь

2022-01-04 11:46 UTC, merged