Module2 task2
htmlacademy-adaptive/1868525-pink-24 pull request #9
Opened 2021-12-03 09:32 UTC by tonkovidav

2021-12-11 19:07 UTC, ozil07 requested changes

2021-12-11 19:07 UTC, ozil07 commented on source/form.html
> +      <input class="main-form__submit" type="submit" value="ОТПРАВИТЬ ФОРМУ">
Используй html5 button

2021-12-11 19:07 UTC, ozil07 commented on source/index.html
> +      <div class="tariffs">
Сделай разметку тарифов таблицей на это обращают внимание при проверке

2021-12-11 19:15 UTC, ozil07 commented
Тег br не используется во всех местах где есть перенос текста, перенос текста в html по умолчанию производится по словам, если в контейнере нет места, поэтому в большей части перенос в предложениях по причине нехватки места. Иногда если есть два предложения их лучше выделить в два отдельных тег p или других, нежели использовать br

Постарайся использовать семантические теги

Используй label для привязки меток к полям формы

2021-12-12 10:57 UTC, tonkovidav commented on source/catalog.html
> +          <ul class="site-list">
Именно этот блок я скопировал у академии на демке)

2021-12-12 11:04 UTC, tonkovidav commented on source/catalog.html
> +        <a href="#">Анна</a>
В последствии это может стать ссылкой на профил пользователя?

2021-12-12 16:31 UTC, tonkovidav commented on source/catalog.html
> +      </div>
Его лучше вынести за пределы списка?
Блок выглядит как и остальные айтемы каталога, за исключением того что фото шире, возможно этот пост открыт. Может добавить ему модификатор "--opened"?

2021-12-12 16:46 UTC, tonkovidav commented on source/catalog.html
> +    <p class="catalog__info-text">Затмите их всех!<br>Выкладывайте все, что накопилось в<br>телефоне!</p>
Возможно каждую отдельную строку обернуть в <p>? Если контент не будет принимать нужную форму по размерам блока.

2021-12-12 16:47 UTC, tonkovidav commented on source/catalog.html
> +      </div>
Сверстать 3 отдельных элемента: отдельно линию и  ползунок в двух состояниях?

2021-12-13 21:23 UTC, ozil07 requested changes
Спасибо за работу, на странице с формой добавь верстку модальных окон, используй класс для всех элементов, убери комментарии со страниц

2021-12-13 21:23 UTC, ozil07 commented on source/catalog.html
> +    <a class="footer__logo-link" href="#">
на внутренних страницах ссылка логотип ведёт на главную

2021-12-13 21:23 UTC, ozil07 commented on source/catalog.html
> +              <a href="./index.html">Главная</a>
Для ссылки на главную в href достаточно добавить / получиться href="/"

2021-12-13 21:23 UTC, ozil07 commented on source/form.html
> +  </div>
Этот блок не относится к шапке сайта

2021-12-13 21:23 UTC, ozil07 commented on source/form.html
> +    <input type="text" class="main-form__data-text" id="surname" placeholder="Укажите фамилию*">
Добавляй атрибут class первым, потому что, он есть у всех элементов

2021-12-13 21:23 UTC, ozil07 commented on source/form.html
> +          <p class="main-form__contacts-title">НОМЕР ТЕЛЕФОНА</p>
Используй label

2021-12-13 21:23 UTC, ozil07 commented on source/form.html
> +            <p class="main-form__contacts-title">АДРЕС ПОЧТЫ</p>
Используй label

2021-12-13 21:23 UTC, ozil07 commented on source/index.html
> +          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6438364490557!2d30.31920306098474!3d59.93805197013344!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca1
Добавь метку на карту

2021-12-16 19:29 UTC, ozil07 requested changes
Спасибо за работу, добавь имена всем полям, используй fieldset для группировки полей

2021-12-16 19:29 UTC, ozil07 commented on source/form.html
> +            <input class="main-form__contacts-text" type="text" id="e-mail" placeholder="Введите почту*">
добавь названия полям

2021-12-16 19:29 UTC, ozil07 commented on source/form.html
> +      <textarea class="main-form__textarea-text" placeholder="Можно прям в красках,не стесняясь в выражениях"></textarea>
Добавь название

2021-12-16 19:29 UTC, ozil07 commented on source/form.html
> +      </div>
Используй fieldset для группировки полей

2021-12-16 19:29 UTC, ozil07 commented on source/form.html
> +      <p class="main-form__note">*&mdash;ОБЯЗАТЕЛЬНЫЕ ПОЛЯ</p>
Используй fieldset для группировки

2021-12-17 09:29 UTC, tonkovidav commented on source/catalog.html
> +        <input class="visualy-hidden" type="range">
Все 3 значения находятся внутри формы, ей задан  action=" https://echo.htmlacademy.ru"
Внизу формы button type="submit". 
Так эти данные не отправятся? 
Или я не понял вопрос?

2021-12-17 09:36 UTC, tonkovidav commented on source/form.html
> +            <input class="main-form__contacts-text" type="text" id="e-mail" placeholder="Введите почту*">
label есть, placeholder есть
Не понял вопрос. Добавить <p>Поле ввода электронной почты</p> для скрин ридера?

2021-12-18 20:58 UTC, ozil07 approved these changes

2021-12-18 20:58 UTC, ozil07 commented on source/form.html
> +            <input class="main-form__contacts-text" type="text" id="e-mail" placeholder="Введите почту*">
чтобы прочитать данные из поля на сервере у поля должен быть атрибут **name**

2021-12-18 20:58 UTC, ozil07 commented on source/catalog.html
> +        <input class="visualy-hidden" type="range">
У тебя на данный момент один range, при передачи этого поля на сервер у тебя передастся одно значение, а в макете 3 фильтра, конечно есть возможность используя один range передать все 3 значения но думаю на этом курсе нужно использовать range

2021-12-18 20:58 UTC, merged